let productos = [
    {
        id: "1",
        categoria: "HAMBURGUESAS",
        nombre: "Hamburguesa clasica",
        descripcion: "Sandwich simple de hamburguesa.",
        img: "../img/hamburguesa.jpg",
        precio: "$300",
    }, {
        id: "2",
        categoria: "HAMBURGUESAS",
        nombre: "Hamburguesa con queso",
        descripcion: "Sandwich de hamburguesa simple con cheddar.",
        img: "../img/hamburguesa-con-queso.jpg",
        precio: "$370",
    }, {
        id: "3",
        categoria: "HAMBURGUESAS",
        nombre: "Hamburguesa doble con cheddar",
        descripcion: "Sandwich de doble hamburguesa con cheddar.",
        img: "../img/hamburguesa-doble.jpg",
        precio: "$670",
    }, {
        id: "4",
        categoria: "HAMBURGUESAS",
        nombre: "Hamburguesa con bacon",
        descripcion: "Sandwich de hamburguesa con bacon, tomate y lechuga.",
        img: "../img/hamburguesa-bacon.jpg",
        precio: "$450",
    }, {
        id: "5",
        categoria: "HAMBURGUESAS",
        nombre: "Hamburguesa triple con queso",
        descripcion: "Sandwich de triple hamburguesa con cheddar.",
        img: "../img/hamburguesa-triple.jpg",
        precio: "$790",
    }, {
        id: "6",
        categoria: "HAMBURGUESAS",
        nombre: "Hamburguesa con guacamole",
        descripcion: "Sandwich de hamburguesa con guacamole casero.",
        img: "../img/hamburguesa-guacamole.jpg",
        precio: "$460",
    }, {
        id: "7",
        categoria: "HAMBURGUESAS",
        nombre: "Hamburguesa de pollo",
        descripcion: "Sandich de hamburguesa de pollo con tomate y lechuga.",
        img: "../img/hamburguesa-pollo.jpg",
        precio: "$330",
    }, {
        id: "8",
        categoria: "HAMBURGUESAS",
        nombre: "Hamburguesa de soja",
        descripcion: "Sandwich de hamburguesa de soja con tomate y lechuga.",
        img: "../img/hamburguesa-soja.jpg",
        precio: "$390",
    }, {
        id: "9",
        categoria: "GUARNICION",
        nombre: "Porcion de papas fritas",
        descripcion: "Porcion de papas fritas.",
        img: "../img/papas-fritas.jpg",
        precio: "$380",
    }, {
        id: "10",
        categoria: "GUARNICION",
        nombre: "Ensalada de lechuga y tomate",
        descripcion: "Ensalada fresca de lechuga y tomate.",
        img: "../img/tomate-lechuga.jpg",
        precio: "$390",
    }, {
        id: "11",
        categoria: "GUARNICION",
        nombre: "Ensalada cesar con pollo",
        descripcion: "Ensalada cesar fresca con trozos de pollo.",
        img: "../img/ensalada-cesar.jpg",
        precio: "$450",
    }, {
        id: "12",
        categoria: "GUARNICION",
        nombre: "Porcion de papas con cheddar",
        descripcion: "Porcion de papas fritas con cheddar.",
        img: "../img/papas-cheddar.jpg",
        precio: "$750",
    }
]